// CERTIFICATE
export const CREATE_CERTIFICATE = "CREATE_CERTIFICATE";
export const CREATE_CERTIFICATE_RED = "CREATE_CERTIFICATE_RED";
export const GET_CERTIFICATE = "GET_CERTIFICATE";
export const GET_CERTIFICATE_RED = "GET_CERTIFICATE_RED";
export const UPDATE_CERTIFICATE = "UPDATE_CERTIFICATE";
export const UPDATE_CERTIFICATE_RED = "UPDATE_CERTIFICATE_RED";
export const DELETE_CERTIFICATE = "DELETE_CERTIFICATE";
export const DELETE_CERTIFICATE_RED = "DELETE_CERTIFICATE_RED";

// CONTACT_US / ENQUIRIES
export const CREATE_CONTACT_US = "CREATE_CONTACT_US";
export const CREATE_CONTACT_US_RED = "CREATE_CONTACT_US_RED";
export const GET_CONTACT_US = "GET_CONTACT_US";
export const GET_CONTACT_US_RED = "GET_CONTACT_US_RED";
export const UPDATE_CONTACT_US = "UPDATE_CONTACT_US";
export const UPDATE_CONTACT_US_RED = "UPDATE_CONTACT_US_RED";
export const DELETE_CONTACT_US = "DELETE_CONTACT_US";
export const DELETE_CONTACT_US_RED = "DELETE_CONTACT_US_RED";

// TESTIMONIALS
export const CREATE_TESTIMONIAL = "CREATE_TESTIMONIAL";
export const CREATE_TESTIMONIAL_RED = "CREATE_TESTIMONIAL_RED";
export const GET_TESTIMONIAL = "GET_TESTIMONIAL";
export const GET_TESTIMONIAL_RED = "GET_TESTIMONIAL_RED";
export const UPDATE_TESTIMONIAL = "UPDATE_TESTIMONIAL";
export const UPDATE_TESTIMONIAL_RED = "UPDATE_TESTIMONIAL_RED";
export const DELETE_TESTIMONIAL = "DELETE_TESTIMONIAL";
export const DELETE_TESTIMONIAL_RED = "DELETE_TESTIMONIAL_RED";

// BLOGS
export const CREATE_BLOG = "CREATE_BLOG";
export const CREATE_BLOG_RED = "CREATE_BLOG_RED";
export const GET_BLOG = "GET_BLOG";
export const GET_BLOG_RED = "GET_BLOG_RED";
export const UPDATE_BLOG = "UPDATE_BLOG";
export const UPDATE_BLOG_RED = "UPDATE_BLOG_RED";
export const DELETE_BLOG = "DELETE_BLOG";
export const DELETE_BLOG_RED = "DELETE_BLOG_RED";

// COURSES / TRACKS
export const CREATE_COURSE = "CREATE_COURSE";
export const CREATE_COURSE_RED = "CREATE_COURSE_RED";
export const GET_COURSE = "GET_COURSE";
export const GET_COURSE_RED = "GET_COURSE_RED";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const UPDATE_COURSE_RED = "UPDATE_COURSE_RED";
export const DELETE_COURSE = "DELETE_COURSE";
export const DELETE_COURSE_RED = "DELETE_COURSE_RED";

// JOBS / VACANCIES
export const CREATE_JOB = "CREATE_JOB";
export const CREATE_JOB_RED = "CREATE_JOB_RED";
export const GET_JOB = "GET_JOB";
export const GET_JOB_RED = "GET_JOB_RED";
export const UPDATE_JOB = "UPDATE_JOB";
export const UPDATE_JOB_RED = "UPDATE_JOB_RED";
export const DELETE_JOB = "DELETE_JOB";
export const DELETE_JOB_RED = "DELETE_JOB_RED";

// APPLICATIONS
export const GET_APPLICATION = "GET_APPLICATION";
export const GET_APPLICATION_RED = "GET_APPLICATION_RED";
export const UPDATE_APPLICATION = "UPDATE_APPLICATION";
export const UPDATE_APPLICATION_RED = "UPDATE_APPLICATION_RED";

// USERS
export const GET_USER = "GET_USER";
export const GET_USER_RED = "GET_USER_RED";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_RED = "UPDATE_USER_RED";
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_RED = "DELETE_USER_RED";
